version: '3.8'

services:
  smart-memo-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_TITLE=スマートメモ帳アプリ
    stdin_open: true
    tty: true
    command: npm start